import React, { useEffect, useRef, useState } from 'react';
import type { AnalyzeResponse, AudienceResponse, CapabilitiesResponse, CommercialResponse, IntentBoardResponse, ResearchGraphResponse } from '@ncos/contracts';
import type { CoreClient } from '@ncos/core-client';
import { message, formatTime } from './common';
import { OpportunityGraph } from './OpportunityGraph';
import { blocked, DataStatus, numberText, TrendLine } from './research-common';
const intentNames: Record<string, string> = { informational: '정보 탐색', howto: '방법', eligibility: '자격·조건', troubleshooting: '문제 해결', comparison_review: '비교·후기', commercial: '구매 고려', local_visit: '지역 방문', other: '기타' };
export function KeywordDetails({ client, analysis, capabilities, onAnalyze, onWatch }: { client: CoreClient; analysis: AnalyzeResponse; capabilities?: CapabilitiesResponse; onAnalyze: (keyword: string) => void; onWatch: (keyword: string) => void }) {
  const [tool, setTool] = useState<'intent' | 'graph' | 'audience' | 'commercial'>('intent');
  const [intent, setIntent] = useState<IntentBoardResponse | null>(null), [graph, setGraph] = useState<ResearchGraphResponse | null>(null), [audience, setAudience] = useState<AudienceResponse | null>(null), [commercial, setCommercial] = useState<CommercialResponse | null>(null);
  const [selected, setSelected] = useState(''), [minimum, setMinimum] = useState(0), [filter, setFilter] = useState('');
  const [device, setDevice] = useState<'PC' | 'MOBILE'>('PC'), [busy, setBusy] = useState(false), [error, setError] = useState('');
  const lock = useRef(false), alive = useRef(true);
  useEffect(() => { alive.current = true; return () => { alive.current = false; }; }, []);
  const node = graph?.nodes.find(n => n.id === selected);
  const target = node?.keyword ?? analysis.keyword;
  const denied = blocked(capabilities, tool === 'intent' ? [] : tool === 'audience' ? ['hub_trend'] : ['searchad']);
  async function run(force = false) {
    if (lock.current || denied) return;
    if (tool !== 'intent' && !window.confirm(`${tool === 'graph' ? '키워드 맵 · 최대 12회' : tool === 'audience' ? '독자 상대 추세 · 최대 15회' : '광고 입찰 참고 · 최대 4회'} 외부 조회를 실행할까요?${force ? ' 저장 캐시를 건너뜁니다.' : ''}`)) return;
    lock.current = true; setBusy(true); setError('');
    try {
      if (tool === 'intent') { const value = await client.getIntentBoard(analysis.snapshot_id); if (alive.current) setIntent(value); }
      else if (tool === 'graph') { const value = await client.graph(analysis.keyword, analysis.snapshot_id, force); if (alive.current) { setGraph(value); setSelected(value.nodes[0]?.id ?? ''); setAudience(null); setCommercial(null); } }
      else if (tool === 'audience') { const value = await client.audience(target, force); if (alive.current) setAudience(value); }
      else { const value = await client.commercial([target], device, force); if (alive.current) setCommercial(value); }
    } catch (e) { if (alive.current) setError(message(e)); }
    finally { lock.current = false; if (alive.current) setBusy(false); }
  }
  return <section className="panel"><h2>키워드 상세 도구</h2><p>기본 분석에서 더 확인하고 싶을 때 사용합니다. 도구를 여는 것만으로 외부 API를 호출하지 않습니다.</p><div className="subnav" aria-label="상세 분석 도구">{([['intent', '의도별 키워드'], ['graph', '키워드 맵'], ['audience', '독자 특성'], ['commercial', '광고 입찰 참고']] as const).map(([key, label]) => <button disabled={busy} key={key} aria-pressed={tool === key} onClick={() => { setTool(key); setError(''); }}>{label}</button>)}</div>
    <p>조회 대상: {tool === 'audience' || tool === 'commercial' ? target : analysis.keyword}{node && (tool === 'audience' || tool === 'commercial') ? ' · 맵에서 선택한 키워드' : ''}</p>{tool === 'commercial' && <><label htmlFor="bid-device">광고 기기</label><select id="bid-device" disabled={busy} value={device} onChange={e => { setDevice(e.target.value as 'PC' | 'MOBILE'); setCommercial(null); }}><option value="PC">PC</option><option value="MOBILE">모바일</option></select></>}
    <div className="action-row"><button disabled={busy || denied} onClick={() => void run()}>{busy ? '조회 중…' : tool === 'intent' ? '저장된 분석으로 의도 보기' : '이 도구 조회'}</button>{tool !== 'intent' && <button disabled={busy || denied} onClick={() => void run(true)}>최신 자료로 다시 조회</button>}</div>{denied && <p role="alert">해당 서비스 사용 한도에 도달했습니다. 앱 설정에서 확인하세요.</p>}{error && <p role="alert" className="notice error">{error}</p>}
    {tool === 'intent' && intent && <><label htmlFor="intent-filter">검색 의도 필터</label><select id="intent-filter" value={filter} onChange={e => setFilter(e.target.value)}><option value="">전체</option>{Object.entries(intentNames).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><p>{formatTime(intent.collected_at)} · {intent.intent_version}</p><div className="table-scroll"><table><thead><tr><th>키워드</th><th>의도</th><th>월 검색량</th><th>상대 추이</th><th>기존 콘텐츠</th></tr></thead><tbody>{intent.items.filter(i => !filter || i.intent === filter).map(i => <tr key={i.keyword}><td><button onClick={() => onAnalyze(i.keyword)}>{i.keyword}</button><details><summary>판정 근거</summary><p>{i.matched_markers.join(', ') || '표현 단서 없음'} · 신뢰도 {i.confidence}</p><p>{i.metric?.source} · {formatTime(i.metric?.collected_at)}</p><p>{i.organic?.note} · {i.commercial.note}</p></details></td><td>{intentNames[i.intent]}</td><td>{i.metric?.masked ? '제한값 포함' : numberText(i.metric?.total)}</td><td>{numberText(i.trend?.latest_ratio, 1)} · {i.trend?.latest_period ?? '미제공'}</td><td>{({ missing: '미작성', draft_only: '원고 있음', published: '공개됨', stale: '최신화 대상', archived: '보관됨' })[i.content.state]} · 원고 {i.content.draft_count}개</td></tr>)}</tbody></table></div></>}
    {tool === 'graph' && graph && <><label htmlFor="minimum-volume">맵 최소 월 검색량</label><input id="minimum-volume" type="number" min={0} value={minimum} onChange={e => setMinimum(Math.max(0, Number(e.target.value)))}/><p>{graph.nodes.length}개 노드 · {graph.edges.length}개 연결 · 호출 {graph.call_budget.actual}/{graph.call_budget.maximum} · {formatTime(graph.collected_at)}</p><OpportunityGraph graph={graph} selectedId={selected} minimumVolume={minimum} onSelect={id => { setSelected(id); setAudience(null); setCommercial(null); }}/>{node && <div className="notice"><h3>{node.keyword}</h3><p>PC {numberText(node.pc_volume)} / 모바일 {numberText(node.mobile_volume)} · 광고 경쟁 {node.competition ?? '자료 없음'} · 블로그 결과 {numberText(node.blog_total)} · 추이 변화 {numberText(node.trend_delta, 2)}</p><p>묶음 {node.cluster} · 자료 상태 {node.enrichment_status}{node.volume_masked ? ' · 검색량 제한값 포함' : ''}</p><div className="action-row"><button onClick={() => onAnalyze(node.keyword)}>이 키워드 재분석</button><button onClick={() => onWatch(node.keyword)}>관심 키워드 추가</button><button onClick={() => setTool('audience')}>독자 특성으로</button><button onClick={() => setTool('commercial')}>광고 입찰 참고로</button></div></div>}</>}
    {tool === 'audience' && audience && <><h3>{audience.keyword} · 독자별 상대 추세</h3><p>{audience.warning || '각 구간은 독립적으로 정규화됩니다. 성별·연령의 실제 인구 비율로 비교하지 마세요.'}</p><DataStatus values={audience.data_status}/>{Object.entries(audience.segments).map(([segment, rows]) => <div key={segment}><h3>{segment}</h3>{rows.map((row, i) => <TrendLine key={i} label={row.label} points={row.points} collectedAt={row.collected_at}/>)}</div>)}</>}
    {tool === 'commercial' && commercial && <><p>광고 입찰 기반 참고값입니다. 콘텐츠 기회 점수와 합산하지 않으며 수익을 보장하지 않습니다. {commercial.score_note}</p><p>{formatTime(commercial.collected_at)} · {commercial.score_version}</p><DataStatus values={commercial.data_status}/><div className="table-scroll"><table><thead><tr><th>키워드/기기</th><th>평균순위 입찰</th><th>최소노출 입찰</th><th>중간입찰</th><th>예상 노출/클릭</th><th>참고 점수</th></tr></thead><tbody>{commercial.rows.map(row => <tr key={row.keyword}><td>{row.keyword} · {row.device}</td><td>{row.average_position_bid == null ? '자료 없음' : `${numberText(row.average_position_bid)}원`}</td><td>{row.minimum_exposure_bid == null ? '자료 없음' : `${numberText(row.minimum_exposure_bid)}원`}</td><td>{row.median_bid == null ? '자료 없음' : `${numberText(row.median_bid)}원`}</td><td>{numberText(row.estimated_impressions)} / {numberText(row.estimated_clicks)}</td><td>{numberText(row.commercial_score, 1)}</td></tr>)}</tbody></table></div></>}
  </section>;
}
