import React from 'react';
import type { AnalyzeResponse } from '@ncos/contracts';
import { PcMobileDonut } from './PcMobileDonut';
import { formatTime } from './common';
import { DataStatus, numberText, safeLink, TrendLine } from './research-common';
export function KeywordAnalysis({ result, onAnalyze, onWrite, onPlan, disabled }: { result: AnalyzeResponse; onAnalyze: (keyword: string) => void; onWrite: () => void; onPlan: () => void; disabled: boolean }) {
  const metric = result.metric;
  return <section className="panel"><div className="section-title"><div><h2>{result.keyword} 분석</h2><p>수집 {formatTime(result.collected_at)} · 분석 #{result.snapshot_id}</p></div><div className="action-row"><button className="primary" onClick={onWrite}>이 키워드로 글쓰기</button><button onClick={onPlan}>근거·콘텐츠 플랜으로</button></div></div>
    <h3 className="section-heading">연관 키워드</h3><p>누르면 해당 키워드로 즉시 재분석합니다. 글은 자동 생성하지 않습니다.</p><div className="keyword-chips">{result.related_keywords.slice(0, 8).map((item, i) => <button key={`${item.keyword}:${i}`} disabled={disabled} onClick={() => onAnalyze(item.keyword)}>{item.keyword}</button>)}</div>{!result.related_keywords.length && <p>관련 자료가 없습니다.</p>}{result.related_keywords.length > 8 && <details><summary>전체 연관 키워드 · {result.related_keywords.length}개</summary><div className="keyword-chips">{result.related_keywords.slice(8).map((item, i) => <button key={`${item.keyword}:${i}`} disabled={disabled} onClick={() => onAnalyze(item.keyword)}>{item.keyword}</button>)}</div></details>}
    <dl className="metric-row"><div><dt>PC 월 검색량</dt><dd>{metric?.volume_masked ? '제한값 포함' : numberText(metric?.monthly_pc_searches)}</dd></div><div><dt>모바일 월 검색량</dt><dd>{metric?.volume_masked ? '제한값 포함' : numberText(metric?.monthly_mobile_searches)}</dd></div><div><dt>광고 경쟁도</dt><dd>{metric?.ad_competition ?? '자료 없음'}</dd></div></dl><p>SearchAd 검색량이며 내 블로그 방문자 수가 아닙니다. {metric ? `자료 수집 ${formatTime(metric.collected_at)}${metric.from_cache ? ' · 캐시 사용' : ''}` : '설정·연결 상태를 확인하세요.'}</p><DataStatus values={result.data_status}/>
    <PcMobileDonut svg pc={metric?.monthly_pc_searches ?? null} mobile={metric?.monthly_mobile_searches ?? null} masked={metric?.volume_masked}/>
    <details className="tool-section"><summary>콘텐츠 기회 점수와 검색 결과 규모</summary><p>기회 점수 {numberText(result.score?.value, 1)} · 신뢰도 {result.score?.confidence ?? '미제공'} · 자료 충족도 {numberText(result.score?.coverage_weight, 2)}</p>{result.score && <><p>산식 {result.score.score_version} · 관측 {result.score.available_component_count}/{result.score.total_component_count}개 · 누락 {result.score.missing.join(', ') || '없음'}</p><div className="table-scroll"><table><thead><tr><th>구성 요소</th><th>가중치</th><th>정규화 값</th><th>점수 기여</th><th>원자료</th></tr></thead><tbody>{result.score.contributions.map(c => <tr key={c.component}><td>{c.component}</td><td>{numberText(c.weight, 2)}</td><td>{numberText(c.normalized, 2)}</td><td>{numberText(c.points, 2)}</td><td>{c.raw} · {c.status === 'ok' ? '관측됨' : '자료 없음'}</td></tr>)}</tbody></table></div></>}<p>블로그 결과 {numberText(result.landscape?.blog_total)} · 카페 {numberText(result.landscape?.cafe_total)} · 지식iN {numberText(result.landscape?.kin_total)} · 웹 {numberText(result.landscape?.web_total)} · 뉴스 {numberText(result.landscape?.news_total)}</p><p>검색 결과 수는 경쟁 강도의 참고치이며 글의 조회수·상위 노출을 보증하지 않습니다.</p><ul>{result.landscape?.top_results.map((item, i) => <li key={i}>{safeLink(item.link) ? <a href={safeLink(item.link)!} target="_blank" rel="noreferrer">{item.title} ↗ 새 탭</a> : item.title}</li>)}</ul></details>
    <details className="tool-section"><summary>검색 추세</summary>{result.trend ? <TrendLine points={result.trend.points} collectedAt={result.trend.collected_at}/> : <p>검색 추세 자료가 없습니다.</p>}</details>
    <details className="tool-section"><summary>실제 질문·주제 묶음</summary><ul>{result.questions.map((q, i) => <li key={i}>{q.text} · {q.channel} · {q.kind === 'review' ? '후기 주제' : '질문'}</li>)}</ul>{!result.questions.length && <p>수집된 질문이 없습니다.</p>}{result.clusters.map((c, i) => <div key={i}><h3>{c.label}</h3><div className="keyword-chips">{c.keywords.map(k => <button key={k} disabled={disabled} onClick={() => onAnalyze(k)}>{k}</button>)}</div></div>)}</details>
  </section>;
}
