import { useQuery } from '@tanstack/react-query';
import type { CoreClient } from '@ncos/core-client';
import type { WritingPreferences } from '@ncos/workbench';

const providers: Record<string, { title: string; purpose: string }> = {
  hub_search: { title: '네이버 검색 자료', purpose: '블로그·뉴스·장소·사진 검색' },
  hub_trend: { title: '검색 추이', purpose: '기간별 상대 검색량 · 급상승 비교' },
  hub_shopping: { title: '쇼핑 추이', purpose: '카테고리별 클릭 추이 · 판매량 아님' },
  searchad: { title: '검색광고 키워드', purpose: '연관어 · 월 검색량 · 입찰 참고치, 읽기 전용' },
};
export function SettingsPanel({ client, preferences, onPreferences, onDisconnect }: { client: CoreClient; preferences: WritingPreferences; onPreferences: (value: WritingPreferences) => void; onDisconnect: () => void }) {
  const health = useQuery({ queryKey: ['web-health'], queryFn: () => client.health() });
  const capabilities = useQuery({ queryKey: ['workbench-capabilities'], queryFn: () => client.capabilities(), staleTime: 30_000 });
  const llm = useQuery({ queryKey: ['workbench-llm'], queryFn: () => client.llmStatus(), retry: false });
  return <div className="settings-grid"><section className="panel"><h2>앱 설정에서 하는 일</h2><p>화면 테마, AI 연결 상태, 네이버 조회 사용량, 글쓰기·임시저장 기본값을 확인합니다. 메뉴를 추가하거나 숨기는 기능이 아닙니다.</p><h3 className="section-heading">글쓰기 AI</h3>{llm.data ? <><p><strong>{llm.data.ready ? '작성 준비됨' : '연결 확인 필요'}</strong> · {llm.data.engine ?? llm.data.provider} · {llm.data.model}</p><p>{llm.data.message}</p>{!llm.data.ready && <p className="notice">{llm.data.action}</p>}</> : <p role="status">AI 상태 확인 중…</p>}<button disabled={llm.isFetching} onClick={() => void llm.refetch()}>AI 상태 다시 확인</button><p>상태 확인만으로 글을 생성하거나 네이버에 저장하지 않습니다. AI 모델과 인증 방식은 로컬 서버 설정에서 변경한 뒤 서버를 재시작합니다.</p></section>
    <section className="panel"><h2>작성과 임시저장 기본값</h2><p>아래 값은 이 브라우저에 자동 저장됩니다. 다른 브라우저·기존 확장과 자동 공유되지 않습니다.</p><label htmlFor="default-blog-id">네이버 블로그 ID</label><input id="default-blog-id" value={preferences.blogId} maxLength={100} placeholder="예: sence4u" onChange={e => onPreferences({ ...preferences, blogId: e.target.value })}/><p>내 블로그 주소의 ID입니다. 네이버 비밀번호를 입력하는 곳이 아닙니다.</p><label htmlFor="default-tags">기본 태그 · 쉼표로 구분</label><input id="default-tags" value={preferences.tags} maxLength={1000} onChange={e => onPreferences({ ...preferences, tags: e.target.value })}/><details className="tool-section"><summary>고급 · 민감 키워드 판별 응답 없음 처리</summary><label className="check-label"><input type="checkbox" checked={preferences.allowSensitiveUnknown} onChange={e => onPreferences({ ...preferences, allowSensitiveUnknown: e.target.checked })}/>판별 API가 응답하지 않아도 AI 작성 허용</label><p>실제로 민감 키워드로 확인되면 기존 차단 정책이 적용됩니다. 완성 원고의 사실·표현 검수는 별도로 필요합니다.</p></details></section>
    <section className="panel settings-wide"><div className="section-title"><div><h2>자료 연결과 API 사용량</h2><p>‘설정됨’은 키가 등록됐다는 뜻이며 실제 권한·연결 성공은 자료 조회 시 확인합니다. 아래 사용량은 이 앱이 기록한 호출량입니다.</p></div><button disabled={capabilities.isFetching} onClick={() => void capabilities.refetch()}>사용량 다시 읽기</button></div><div className="provider-grid">{Object.entries(capabilities.data?.providers ?? {}).map(([id, item]) => <article className="provider-card" key={id}><h3>{providers[id]?.title ?? id}</h3><p>{providers[id]?.purpose ?? '상세 분석 자료'}</p><p><strong>{item.status === 'configured' ? '설정됨 · 실제 권한 미검증' : item.status === 'unconfigured' ? '키 설정 필요' : item.status}</strong></p>{item.quota ? <><p>월 {item.quota.monthly.used.toLocaleString('ko-KR')} / {item.quota.monthly.limit.toLocaleString('ko-KR')}회</p>{item.quota.daily && <p>일 {item.quota.daily.used.toLocaleString('ko-KR')} / {item.quota.daily.limit.toLocaleString('ko-KR')}회</p>}<p>{item.quota.blocked ? '사용 한도 도달 · 추가 조회 제한' : item.quota.warning ? '사용량 주의' : '설정된 한도 내'}</p></> : <p>사용량 정보 없음 · 0회라는 의미가 아닙니다.</p>}</article>)}</div><p>API 비밀키는 웹 화면에 표시하거나 저장하지 않습니다. 키 변경은 프로젝트의 로컬 <code>.env</code>에서 진행하고 서버를 재시작하세요.</p></section>
    <section className="panel settings-wide"><h2>로컬 앱 연결과 네이버 로그인은 별개입니다</h2><p>앱 연결은 이 컴퓨터의 원고에 접근하는 권한입니다. 네이버 로그인 성공을 뜻하지 않습니다. 네이버 임시저장은 별도 로그인 브라우저 연결을 실행 시 확인합니다.</p><dl className="status-list"><dt>서버 상태</dt><dd>{health.data?.status === 'ok' ? '응답 정상' : '확인 중'}</dd><dt>이 브라우저 인증</dt><dd>보호된 세션 쿠키 · 최대 8시간 · 서버 원고와 API 비밀키는 삭제하지 않음</dd><dt>저장 구분</dt><dd>내 원고 저장 = 로컬 보관 / 네이버 임시저장 = 비공개 편집기 보관 / 공개 완료 등록 = 이미 발행한 글의 기록</dd></dl><button onClick={onDisconnect}>이 브라우저 연결 종료</button></section>
    {[health.error, capabilities.error, llm.error].filter(Boolean).map((e, i) => <p role="alert" className="notice error settings-wide" key={i}>{e instanceof Error ? e.message : '연결 상태를 확인하지 못했습니다.'}</p>)}
  </div>;
}
