"""phase3 core tables

Revision ID: 57355a3d51d1
Revises: 
Create Date: 2026-09-01 21:15:46.159616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57355a3d51d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_cache_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_cache_provider'), ['provider'], unique=False)

    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('period', sa.String(length=6), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'period', name='uq_api_usage_provider_period')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keywords_text'), ['text'], unique=True)

    op.create_table('keyword_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('score', sa.JSON(), nullable=True),
    sa.Column('score_version', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('keyword_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_keyword_snapshots_keyword_id'), ['keyword_id'], unique=False)

    op.create_table('serp_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('serp_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serp_snapshots_keyword_id'), ['keyword_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serp_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serp_snapshots_keyword_id'))

    op.drop_table('serp_snapshots')
    with op.batch_alter_table('keyword_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keyword_snapshots_keyword_id'))

    op.drop_table('keyword_snapshots')
    with op.batch_alter_table('keywords', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_keywords_text'))

    op.drop_table('keywords')
    op.drop_table('api_usage')
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_cache_provider'))
        batch_op.drop_index(batch_op.f('ix_api_cache_expires_at'))

    op.drop_table('api_cache')
    # ### end Alembic commands ###
