"""phase6 drafts and publish jobs

Revision ID: a60d442bc8dd
Revises: 57355a3d51d1
Create Date: 2026-09-01 21:36:39.099920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60d442bc8dd'
down_revision: Union[str, Sequence[str], None] = '57355a3d51d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('plan_order', sa.Integer(), nullable=True),
    sa.Column('blog_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drafts_keyword_id'), ['keyword_id'], unique=False)

    op.create_table('draft_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'version', name='uq_draft_versions_draft_version')
    )
    with op.batch_alter_table('draft_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_draft_versions_draft_id'), ['draft_id'], unique=False)

    op.create_table('publish_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('publish_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_publish_jobs_draft_id'), ['draft_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('publish_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_publish_jobs_draft_id'))

    op.drop_table('publish_jobs')
    with op.batch_alter_table('draft_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_versions_draft_id'))

    op.drop_table('draft_versions')
    with op.batch_alter_table('drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drafts_keyword_id'))

    op.drop_table('drafts')
    # ### end Alembic commands ###
